const mongoose = require("mongoose");
const dotenv = require("dotenv");
const Community = require("../models/Community");

dotenv.config();

const communities = [
  {
    title: "Reactiflux",
    description:
      "Largest React.js community for discussions, help, and events.",
    tech_stack: "Web (React/JS)",
    platform: "Discord",
    location_mode: "Global/Online",
    tags: ["React", "JavaScript", "Frontend", "Beginners"],
    joining_link: "https://www.reactiflux.com/",
    member_count: 150000,
    activity_level: "High",
  },
  {
    title: "Nodeiflux",
    description:
      "Backend-focused Node.js community for queries, updates, and gigs.",
    tech_stack: "Backend (Node)",
    platform: "Discord",
    location_mode: "Global/Online",
    tags: ["Node.js", "Backend", "JavaScript"],
    joining_link: "https://nodeiflux.com/",
    member_count: 14000,
    activity_level: "High",
  },
  {
    title: "Python Discord",
    description:
      "Official Python community for novices and experts, with contests.",
    tech_stack: "Backend (Python)",
    platform: "Discord",
    location_mode: "Global/Online",
    tags: ["Python", "Beginners", "Data Science"],
    joining_link: "https://pythondiscord.com/",
    member_count: 170000,
    activity_level: "High",
  },
  {
    title: "TensorFlow Discord",
    description:
      "For deep learning, AI, and ML discussions with Google support.",
    tech_stack: "ML/AI",
    platform: "Discord",
    location_mode: "Global/Online",
    tags: ["TensorFlow", "AI", "Machine Learning"],
    joining_link: "https://discord.gg/tensorflow",
    member_count: 8000,
    activity_level: "Medium",
  },
  {
    title: "Learn AI Together",
    description: "AI enthusiasts sharing papers, projects, and Kaggle tips.",
    tech_stack: "ML/AI",
    platform: "Discord",
    location_mode: "Global/Online",
    tags: ["AI", "Kaggle", "Courses"],
    joining_link: "https://discord.gg/learn-ai-together",
    member_count: 43000,
    activity_level: "High",
  },
  {
    title: "The Programmer's Hangout",
    description: "General coding help for all levels, with 90k+ members.",
    tech_stack: "General",
    platform: "Discord",
    location_mode: "Global/Online",
    tags: ["Coding", "Help", "Beginners"],
    joining_link: "https://discord.gg/programmers",
    member_count: 90000,
    activity_level: "High",
  },
  {
    title: "Coding Den",
    description:
      "Beginner-friendly for Java, Python, databases; includes giveaways.",
    tech_stack: "General",
    platform: "Discord",
    location_mode: "Global/Online",
    tags: ["Beginners", "Java", "Python"],
    joining_link: "https://discord.gg/codingden",
    member_count: 50000,
    activity_level: "High",
  },
  {
    title: "SpeakJS",
    description: "JavaScript community for newbies and pros.",
    tech_stack: "Web (React/JS)",
    platform: "Discord",
    location_mode: "Global/Online",
    tags: ["JavaScript", "Frontend"],
    joining_link: "https://discord.gg/speakjs",
    member_count: 20000,
    activity_level: "Medium",
  },
  {
    title: "CodeSupport",
    description: "Language-agnostic coding support with strict rules.",
    tech_stack: "General",
    platform: "Discord",
    location_mode: "Global/Online",
    tags: ["Support", "Coding"],
    joining_link: "https://discord.gg/codesupport",
    member_count: 15000,
    activity_level: "Medium",
  },
  {
    title: "Lazy Developer",
    description: "Beginners learning skills, open-source projects.",
    tech_stack: "General",
    platform: "Discord",
    location_mode: "Global/Online",
    tags: ["Beginners", "Open Source"],
    joining_link: "https://discord.gg/lazydev",
    member_count: 10000,
    activity_level: "Medium",
  },
  {
    title: "Programmer Humor",
    description: "Fun memes and unwinding for developers.",
    tech_stack: "General",
    platform: "Discord",
    location_mode: "Global/Online",
    tags: ["Humor", "Relax"],
    joining_link: "https://discord.gg/programmerhumor",
    member_count: 25000,
    activity_level: "High",
  },
  {
    title: "/r/LearnMachineLearning",
    description: "Reddit-based ML study group.",
    tech_stack: "ML/AI",
    platform: "Reddit",
    location_mode: "Global/Online",
    tags: ["Machine Learning", "Study"],
    joining_link: "https://www.reddit.com/r/learnmachinelearning/",
    member_count: 500000,
    activity_level: "High",
  },
  {
    title: "AI Mastermind Hub",
    description: "AI brainstorming and resources.",
    tech_stack: "ML/AI",
    platform: "Discord",
    location_mode: "Global/Online",
    tags: ["AI", "Brainstorm"],
    joining_link: "https://discord.gg/ai-mastermind",
    member_count: 12000,
    activity_level: "Medium",
  },
  {
    title: "Pure AI",
    description: "Pure AI discussions and tools.",
    tech_stack: "ML/AI",
    platform: "Discord",
    location_mode: "Global/Online",
    tags: ["AI", "Tools"],
    joining_link: "https://discord.gg/pureai",
    member_count: 8000,
    activity_level: "Medium",
  },
  {
    title: "Fundamentals ML",
    description: "Basics of machine learning for beginners.",
    tech_stack: "ML/AI",
    platform: "Discord",
    location_mode: "Global/Online",
    tags: ["Beginners", "ML"],
    joining_link: "https://discord.gg/fundamentalsml",
    member_count: 5000,
    activity_level: "Medium",
  },
  {
    title: "Dose of Data",
    description: "Data science daily insights.",
    tech_stack: "ML/AI/Data Science",
    platform: "Discord",
    location_mode: "Global/Online",
    tags: ["Data Science"],
    joining_link: "https://discord.gg/doseofdata",
    member_count: 10000,
    activity_level: "High",
  },
  {
    title: "The #1 Artificial Intelligence Class",
    description: "Structured AI learning classes.",
    tech_stack: "ML/AI",
    platform: "Discord",
    location_mode: "Global/Online",
    tags: ["AI", "Classes"],
    joining_link: "https://discord.gg/ai-class",
    member_count: 15000,
    activity_level: "High",
  },
  {
    title: "Artificial Intelligence Community",
    description: "General AI networking.",
    tech_stack: "ML/AI",
    platform: "Discord",
    location_mode: "Global/Online",
    tags: ["AI", "Networking"],
    joining_link: "https://discord.gg/aicommunity",
    member_count: 5000,
    activity_level: "Medium",
  },
  {
    title: "Fast.ai",
    description: "Practical deep learning courses community.",
    tech_stack: "ML/AI",
    platform: "Discord",
    location_mode: "Global/Online",
    tags: ["Deep Learning"],
    joining_link: "https://discord.gg/fastai",
    member_count: 20000,
    activity_level: "High",
  },
  {
    title: "AI BusinessPlans",
    description: "AI for business and planning.",
    tech_stack: "ML/AI",
    platform: "Discord",
    location_mode: "Global/Online",
    tags: ["AI", "Business"],
    joining_link: "https://discord.gg/aibusiness",
    member_count: 3000,
    activity_level: "Medium",
  },
  {
    title: "The Data Share",
    description: "Sharing datasets and ML projects.",
    tech_stack: "ML/AI/Data Science",
    platform: "Discord",
    location_mode: "Global/Online",
    tags: ["Datasets", "Projects"],
    joining_link: "https://discord.gg/thedatashare",
    member_count: 4000,
    activity_level: "Medium",
  },
  {
    title: "Darknet/YOLO Object Detection",
    description: "Focus on computer vision and YOLO.",
    tech_stack: "ML/AI",
    platform: "Discord",
    location_mode: "Global/Online",
    tags: ["Computer Vision", "YOLO"],
    joining_link: "https://discord.gg/darknet",
    member_count: 6000,
    activity_level: "Medium",
  },
  {
    title: "Grateful Labs",
    description: "AI research and labs collaboration.",
    tech_stack: "ML/AI",
    platform: "Discord",
    location_mode: "Global/Online",
    tags: ["Research"],
    joining_link: "https://discord.gg/gratefullabs",
    member_count: 2000,
    activity_level: "Low",
  },
  {
    title: "MLOps",
    description: "Machine learning operations best practices.",
    tech_stack: "ML/AI",
    platform: "Discord",
    location_mode: "Global/Online",
    tags: ["MLOps"],
    joining_link: "https://discord.gg/mlops",
    member_count: 14000,
    activity_level: "High",
  },
  {
    title: "Arc Community",
    description: "Remote devs networking and career advice.",
    tech_stack: "General",
    platform: "Slack",
    location_mode: "Global/Online",
    tags: ["Remote Work", "Career"],
    joining_link: "https://arc.dev/community",
    member_count: 50000,
    activity_level: "High",
  },
  {
    title: "GitHub Community",
    description: "Code collaboration and open source hub.",
    tech_stack: "Open Source/GSoC",
    platform: "GitHub",
    location_mode: "Global/Online",
    tags: ["Open Source", "Collaboration"],
    joining_link: "https://github.com/community",
    member_count: 40000000,
    activity_level: "High",
  },
  {
    title: "Stack Overflow",
    description: "Q&A for coding problems.",
    tech_stack: "General",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["Q&A", "Troubleshooting"],
    joining_link: "https://stackoverflow.com/",
    member_count: 100000000,
    activity_level: "High",
  },
  {
    title: "Reddit r/webdev",
    description: "Front-end and back-end web dev discussions.",
    tech_stack: "Web (React/JS)",
    platform: "Reddit",
    location_mode: "Global/Online",
    tags: ["Web Dev", "Frontend"],
    joining_link: "https://www.reddit.com/r/webdev/",
    member_count: 500000,
    activity_level: "High",
  },
  {
    title: "Dev.to",
    description: "Blogging and dev discussions.",
    tech_stack: "General",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["Blogging", "Sharing"],
    joining_link: "https://dev.to/",
    member_count: 700000,
    activity_level: "High",
  },
  {
    title: "Codementor Community",
    description: "Mentoring and idea exchange.",
    tech_stack: "General",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["Mentoring"],
    joining_link: "https://www.codementor.io/community",
    member_count: 100000,
    activity_level: "Medium",
  },
  {
    title: "GameDev.net",
    description: "Game design tutorials and forums.",
    tech_stack: "Game Dev",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["Game Dev", "Tutorials"],
    joining_link: "https://www.gamedev.net/",
    member_count: 500000,
    activity_level: "Medium",
  },
  {
    title: "Unity Forum",
    description: "Unity engine support and trends.",
    tech_stack: "Game Dev",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["Unity", "Game Dev"],
    joining_link: "https://forum.unity.com/",
    member_count: 1000000,
    activity_level: "High",
  },
  {
    title: "Game Dev League (Discord)",
    description: "Game dev showcases and discussions.",
    tech_stack: "Game Dev",
    platform: "Discord",
    location_mode: "Global/Online",
    tags: ["Game Dev"],
    joining_link: "https://discord.com/invite/gamedev",
    member_count: 50000,
    activity_level: "High",
  },
  {
    title: "Official Python Forum",
    description: "Global Python career and work discussions.",
    tech_stack: "Backend (Python)",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["Python", "Career"],
    joining_link: "https://discuss.python.org/",
    member_count: 200000,
    activity_level: "High",
  },
  {
    title: "Real Python Slack",
    description: "Tutorials and career Q&A.",
    tech_stack: "Backend (Python)",
    platform: "Slack",
    location_mode: "Global/Online",
    tags: ["Python", "Tutorials"],
    joining_link: "https://realpython.com/community/",
    member_count: 50000,
    activity_level: "Medium",
  },
  {
    title: "PySlackers",
    description: "Inclusive Python Slack for all devs.",
    tech_stack: "Backend (Python)",
    platform: "Slack",
    location_mode: "Global/Online",
    tags: ["Python"],
    joining_link: "https://pyslackers.com/web",
    member_count: 20000,
    activity_level: "High",
  },
  {
    title: "Webdeveloper.com",
    description: "HTML, CSS, Ruby, SQL forums.",
    tech_stack: "Web (React/JS)",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["Web Dev", "Beginners"],
    joining_link: "https://www.webdeveloper.com/",
    member_count: 100000,
    activity_level: "Medium",
  },
  {
    title: "CodeProject",
    description: "Articles and technical Q&A.",
    tech_stack: "Web (React/JS)",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["Programming", "Articles"],
    joining_link: "https://www.codeproject.com/",
    member_count: 1000000,
    activity_level: "High",
  },
  {
    title: "Hashnode",
    description: "Dev blogging and feedback.",
    tech_stack: "General",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["Blogging", "Feedback"],
    joining_link: "https://hashnode.com/",
    member_count: 500000,
    activity_level: "High",
  },
  {
    title: "XDA Developers",
    description: "Android dev info and forums.",
    tech_stack: "Mobile (Android)",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["Android"],
    joining_link: "https://www.xda-developers.com/",
    member_count: 1000000,
    activity_level: "High",
  },
  {
    title: "Apple Developer Forums",
    description: "iOS/macOS dev with Apple engineers.",
    tech_stack: "Mobile (iOS)",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["iOS", "Swift"],
    joining_link: "https://developer.apple.com/forums/",
    member_count: 500000,
    activity_level: "High",
  },
  {
    title: "iOS Developers Slack",
    description: "iOS app dev enthusiasts.",
    tech_stack: "Mobile (iOS)",
    platform: "Slack",
    location_mode: "Global/Online",
    tags: ["iOS"],
    joining_link: "https://ios-developers.io/",
    member_count: 35000,
    activity_level: "High",
  },
  {
    title: "MacRumors Forums",
    description: "iOS/Mac updates and dev forums.",
    tech_stack: "Mobile (iOS)",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["iOS", "Mac"],
    joining_link: "https://forums.macrumors.com/",
    member_count: 2000000,
    activity_level: "High",
  },
  {
    title: "r/iOSProgramming",
    description: "iOS code samples and projects.",
    tech_stack: "Mobile (iOS)",
    platform: "Reddit",
    location_mode: "Global/Online",
    tags: ["iOSProgramming"],
    joining_link: "https://www.reddit.com/r/iOSProgramming/",
    member_count: 114000,
    activity_level: "High",
  },
  {
    title: "iOS on Stack Overflow",
    description: "iOS-specific Q&A.",
    tech_stack: "Mobile (iOS)",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["iOS", "Objective-C"],
    joining_link: "https://stackoverflow.com/questions/tagged/ios",
    member_count: 1000000,
    activity_level: "High",
  },
  {
    title: "Java Programming Forums",
    description: "Java code help and resources.",
    tech_stack: "Backend",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["Java"],
    joining_link: "https://www.javaprogrammingforums.com/",
    member_count: 80000,
    activity_level: "Medium",
  },
  {
    title: "Oracle Java Community",
    description: "Official Java discussions.",
    tech_stack: "Backend",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["Java"],
    joining_link:
      "https://community.oracle.com/tech/developers/categories/13287-java",
    member_count: 500000,
    activity_level: "High",
  },
  {
    title: "Meteor Forum",
    description: "JS framework guides and meetups.",
    tech_stack: "Web (React/JS)",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["Meteor", "JS"],
    joining_link: "https://forums.meteor.com/",
    member_count: 50000,
    activity_level: "Medium",
  },
  {
    title: "Ember Discuss",
    description: "Ember.js Q&A on CLI and models.",
    tech_stack: "Web (React/JS)",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["Ember.js"],
    joining_link: "https://discuss.emberjs.com/",
    member_count: 10000,
    activity_level: "Medium",
  },
  {
    title: "Vue.JS Forum",
    description: "Vue discussions in multiple languages.",
    tech_stack: "Web (React/JS)",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["Vue.js"],
    joining_link: "https://forum.vuejs.org/",
    member_count: 50000,
    activity_level: "High",
  },
  {
    title: "r/Frontend",
    description: "Frontend tips and links.",
    tech_stack: "Web (React/JS)",
    platform: "Reddit",
    location_mode: "Global/Online",
    tags: ["Frontend", "HTML5"],
    joining_link: "https://www.reddit.com/r/Frontend/",
    member_count: 200000,
    activity_level: "High",
  },
  {
    title: "#FrontEndDevelopers",
    description: "Creative frontend exchange and gigs.",
    tech_stack: "Web (React/JS)",
    platform: "Discord",
    location_mode: "Global/Online",
    tags: ["Frontend"],
    joining_link: "https://frontenddevelopers.org/",
    member_count: 10000,
    activity_level: "Medium",
  },
  {
    title: "Making WordPress Slack",
    description: "WordPress code and design contributions.",
    tech_stack: "Web (React/JS)",
    platform: "Slack",
    location_mode: "Global/Online",
    tags: ["WordPress"],
    joining_link: "https://wordpress.slack.com/",
    member_count: 50000,
    activity_level: "High",
  },
  {
    title: "WordPress Support Forum",
    description: "Troubleshooting and plugins.",
    tech_stack: "Web (React/JS)",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["WordPress", "Plugins"],
    joining_link: "https://wordpress.org/support/",
    member_count: 1000000,
    activity_level: "High",
  },
  {
    title: "WP Devs Stack Exchange",
    description: "WordPress Q&A.",
    tech_stack: "Web (React/JS)",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["WordPress"],
    joining_link: "https://wordpress.stackexchange.com/",
    member_count: 200000,
    activity_level: "High",
  },
  {
    title: "r/rails",
    description: "Ruby on Rails daily content.",
    tech_stack: "Backend",
    platform: "Reddit",
    location_mode: "Global/Online",
    tags: ["Ruby on Rails"],
    joining_link: "https://www.reddit.com/r/rails/",
    member_count: 75000,
    activity_level: "High",
  },
  {
    title: "r/ruby",
    description: "Ruby enthusiasts subreddit.",
    tech_stack: "Backend",
    platform: "Reddit",
    location_mode: "Global/Online",
    tags: ["Ruby"],
    joining_link: "https://www.reddit.com/r/ruby/",
    member_count: 75000,
    activity_level: "High",
  },
  {
    title: "Ruby & RoR on Stack Overflow",
    description: "Ruby knowledge sharing.",
    tech_stack: "Backend",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["Ruby", "Rails"],
    joining_link: "https://stackoverflow.com/questions/tagged/ruby-on-rails",
    member_count: 500000,
    activity_level: "High",
  },
  {
    title: "PHP on Stack Overflow",
    description: "PHP news and docs.",
    tech_stack: "Backend",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["PHP"],
    joining_link: "https://stackoverflow.com/questions/tagged/php",
    member_count: 1000000,
    activity_level: "High",
  },
  {
    title: "PHP DN",
    description: "PHP assistance and friendship.",
    tech_stack: "Backend",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["PHP"],
    joining_link: "https://www.devnetwork.net/",
    member_count: 50000,
    activity_level: "Medium",
  },
  {
    title: "PHP Builder",
    description: "PHP app building threads.",
    tech_stack: "Backend",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["PHP"],
    joining_link: "https://board.phpbuilder.com/",
    member_count: 100000,
    activity_level: "Medium",
  },
  {
    title: "PHP-FIG",
    description: "PHP standards discussions.",
    tech_stack: "Backend",
    platform: "Discord",
    location_mode: "Global/Online",
    tags: ["PHP", "Standards"],
    joining_link: "https://www.php-fig.org/get-involved/",
    member_count: 10000,
    activity_level: "Medium",
  },
  {
    title: "r/PHP",
    description: "PHP news and opinions.",
    tech_stack: "Backend",
    platform: "Reddit",
    location_mode: "Global/Online",
    tags: ["PHP"],
    joining_link: "https://www.reddit.com/r/PHP/",
    member_count: 200000,
    activity_level: "High",
  },
  {
    title: "The PHP Developer Network",
    description: "PHP, MySQL, Drupal group.",
    tech_stack: "Backend",
    platform: "LinkedIn",
    location_mode: "Global/Online",
    tags: ["PHP", "MySQL"],
    joining_link: "https://www.linkedin.com/groups/2195403/",
    member_count: 50000,
    activity_level: "Medium",
  },
  {
    title: "LambdaTest Community",
    description: "Testing and web dev discussions.",
    tech_stack: "General",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["Testing", "Web Dev"],
    joining_link: "https://community.lambdatest.com/",
    member_count: 50000,
    activity_level: "High",
  },
  {
    title: "Google Developers Group",
    description: "Google tech events and workshops.",
    tech_stack: "General",
    platform: "Meetup",
    location_mode: "Global/Online",
    tags: ["Google", "Flutter"],
    joining_link: "https://gdg.community.dev/",
    member_count: 1000000,
    activity_level: "High",
  },
  {
    title: "Microsoft Developer Community",
    description: "Azure and .NET learning.",
    tech_stack: "General",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["Azure", ".NET"],
    joining_link: "https://developer.microsoft.com/en-us/",
    member_count: 500000,
    activity_level: "High",
  },
  {
    title: "Android Community",
    description: "Android open-source contributions.",
    tech_stack: "Mobile (Android)",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["Android"],
    joining_link: "https://support.google.com/android/community",
    member_count: 1000000,
    activity_level: "High",
  },
  {
    title: "CodePen",
    description: "Front-end prototyping and sharing.",
    tech_stack: "Web (React/JS)",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["HTML", "CSS", "JS"],
    joining_link: "https://codepen.io/",
    member_count: 1000000,
    activity_level: "High",
  },
  {
    title: "freeCodeCamp Forum",
    description: "Free coding lessons and certifications.",
    tech_stack: "General",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["Free Coding", "Certifications"],
    joining_link: "https://forum.freecodecamp.org/",
    member_count: 500000,
    activity_level: "High",
  },
  {
    title: "Kaggle",
    description: "Data science competitions and notebooks.",
    tech_stack: "ML/AI/Data Science",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["Kaggle", "Competitions"],
    joining_link: "https://www.kaggle.com/",
    member_count: 15000000,
    activity_level: "High",
  },
  {
    title: "LeetCode",
    description: "Coding challenges for interviews.",
    tech_stack: "General",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["Algorithms", "Interviews"],
    joining_link: "https://leetcode.com/",
    member_count: 5000000,
    activity_level: "High",
  },
  {
    title: "Mozilla Web Docs Community",
    description: "Web tech docs and contributions.",
    tech_stack: "Web (React/JS)",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["Web APIs", "Documentation"],
    joining_link: "https://developer.mozilla.org/en-US/docs/MDN/Community",
    member_count: 1000000,
    activity_level: "High",
  },
  {
    title: "Discord Developers",
    description: "Bot building and app integration.",
    tech_stack: "General",
    platform: "Discord",
    location_mode: "Global/Online",
    tags: ["Bots", "SDK"],
    joining_link: "https://discord.com/developers",
    member_count: 500000,
    activity_level: "High",
  },
  {
    title: "HackerNoon",
    description: "Tech stories and lessons.",
    tech_stack: "General",
    platform: "Forum",
    location_mode: "Global/Online",
    tags: ["Stories", "AI"],
    joining_link: "https://hackernoon.com/",
    member_count: 1000000,
    activity_level: "Medium",
  },
];

async function seedDatabase() {
  try {
    await mongoose.connect(
      process.env.MONGODB_URI || "mongodb://localhost:27017/devlinker"
    );
    console.log(" Connected to MongoDB");

    // Clear existing communities
    await Community.deleteMany({});
    console.log(" Cleared existing communities");

    // Insert communities
    await Community.insertMany(communities);
    console.log(` Seeded ${communities.length} communities`);

    process.exit(0);
  } catch (error) {
    console.error(" Error seeding database:", error);
    process.exit(1);
  }
}

seedDatabase();
